### PR TITLE
Poll wifi signal strength when the screen is on and wifi connection it active.

### PR DESCRIPTION
**Pull request by monich**
Signal strength is polled from wpa_supplicant with SignalPoll which is not supposed disturb active connections or affect throughput in any way. Signal strength is queried every 2 seconds and averaged for the last 10 seconds.

### CODE REVIEW

**Comment by lpotter** [comment]
Does SignalPoll get the current rssi or a cached value?

**Comment by monich** [comment]
Looks like the current value to me (it changes quite quickly if you are moving around) but I guess it's driver specific. Works well on both tablet and phone.

**Comment by lpotter** [comment]
LGTM

**Comment by monich** [comment]
Rebased, will wait for @tigeli to confirm this one.

**Comment by tigeli** [comment]
Seems to be working, but I've got two crashes without proper backtraces with this..

**Comment by monich** [comment]
@tigeli the crashes are clearly caused by https://github.com/mer-packages/connman/pull/224. I'll roll it back.

**Comment by monich** [comment]
Rolled back https://github.com/monich/connman/commit/92e1fff and https://github.com/monich/connman/commit/538238b, and rebased again.

**Comment by tigeli** [comment]
LGTM

**Pull request merged**
